name: Deploy to Github Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [master]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
      
    - name: Publish .NET Core Project
      run: dotnet publish SampleAPI.csproj -c Release -o release --nologo
      
    - name: Commit wwwroot to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
